[package]
name = "mahe"
version = "0.1.0"
authors = ["Joe Corcoran <joe@corcoran.io>"]

[dependencies]
clap = { version = "~2.10", features = ["wrap_help", "suggestions"] }
hyper = "~0.9"
reroute = "*"
